data={
    "zhongguo":{
        "beijing":{
            "dongchengqu":"mahua",
            "xichengqu":"hutong"
        },
        "shanghai":{
            "minhangqu":"henhao",
            "pudongqu":"couhe"
        }
    },
    "meiguo":{
            "kenlindun":{
                "zongtong":"aobama",
                "furen":"yingfeinidi"
            },
            "xiaodao":{
                "meizhou":"meixiaodao",
                "feizhou":"feixiaodao"
            }
        }
}
